name: Link Check

on:
  schedule:
    # Run every Wednesday at 8am to check URL links still resolve
    - cron: "0 8 * * WED"

jobs:
  docs:
    strategy:
      fail-fast: false

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install python packages
        uses: ./.github/actions/install_requirements
        with:
          requirements_file: requirements-dev-3.x.txt
          install_options: -e .[dev]

      - name: Check links
        run: tox -e docs -- -b linkcheck

      - name: Keepalive Workflow
        uses: gautamkrishnar/keepalive-workflow@v1
